# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: store.proto for package 'store.v1'

require 'grpc'
require 'store_pb'

module Store
  module V1
    module StoreService
      # StoreService provides CRUD operations for store items
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'store.v1.StoreService'

        # CreateItem creates a new store item
        rpc :CreateItem, ::Store::V1::CreateItemRequest, ::Store::V1::CreateItemResponse
        # GetItem retrieves an item by ID
        rpc :GetItem, ::Store::V1::GetItemRequest, ::Store::V1::GetItemResponse
        # UpdateItem updates an existing item
        rpc :UpdateItem, ::Store::V1::UpdateItemRequest, ::Store::V1::UpdateItemResponse
        # DeleteItem removes an item (soft delete by setting status to DISCONTINUED)
        rpc :DeleteItem, ::Store::V1::DeleteItemRequest, ::Store::V1::DeleteItemResponse
        # ListItems lists items with optional filtering and pagination
        rpc :ListItems, ::Store::V1::ListItemsRequest, ::Store::V1::ListItemsResponse
        # UpdateInventory updates the inventory count for an item
        rpc :UpdateInventory, ::Store::V1::UpdateInventoryRequest, ::Store::V1::UpdateInventoryResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
