// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: store.proto

package storeproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ItemCategory represents different types of store items
type ItemCategory int32

const (
	ItemCategory_ITEM_CATEGORY_UNSPECIFIED ItemCategory = 0
	ItemCategory_ITEM_CATEGORY_ELECTRONICS ItemCategory = 1
	ItemCategory_ITEM_CATEGORY_CLOTHING    ItemCategory = 2
	ItemCategory_ITEM_CATEGORY_BOOKS       ItemCategory = 3
	ItemCategory_ITEM_CATEGORY_HOME        ItemCategory = 4
	ItemCategory_ITEM_CATEGORY_SPORTS      ItemCategory = 5
)

// Enum value maps for ItemCategory.
var (
	ItemCategory_name = map[int32]string{
		0: "ITEM_CATEGORY_UNSPECIFIED",
		1: "ITEM_CATEGORY_ELECTRONICS",
		2: "ITEM_CATEGORY_CLOTHING",
		3: "ITEM_CATEGORY_BOOKS",
		4: "ITEM_CATEGORY_HOME",
		5: "ITEM_CATEGORY_SPORTS",
	}
	ItemCategory_value = map[string]int32{
		"ITEM_CATEGORY_UNSPECIFIED": 0,
		"ITEM_CATEGORY_ELECTRONICS": 1,
		"ITEM_CATEGORY_CLOTHING":    2,
		"ITEM_CATEGORY_BOOKS":       3,
		"ITEM_CATEGORY_HOME":        4,
		"ITEM_CATEGORY_SPORTS":      5,
	}
)

func (x ItemCategory) Enum() *ItemCategory {
	p := new(ItemCategory)
	*p = x
	return p
}

func (x ItemCategory) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ItemCategory) Descriptor() protoreflect.EnumDescriptor {
	return file_store_proto_enumTypes[0].Descriptor()
}

func (ItemCategory) Type() protoreflect.EnumType {
	return &file_store_proto_enumTypes[0]
}

func (x ItemCategory) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ItemCategory.Descriptor instead.
func (ItemCategory) EnumDescriptor() ([]byte, []int) {
	return file_store_proto_rawDescGZIP(), []int{0}
}

// ItemStatus represents the current status of an item
type ItemStatus int32

const (
	ItemStatus_ITEM_STATUS_UNSPECIFIED  ItemStatus = 0
	ItemStatus_ITEM_STATUS_ACTIVE       ItemStatus = 1
	ItemStatus_ITEM_STATUS_INACTIVE     ItemStatus = 2
	ItemStatus_ITEM_STATUS_OUT_OF_STOCK ItemStatus = 3
	ItemStatus_ITEM_STATUS_DISCONTINUED ItemStatus = 4
)

// Enum value maps for ItemStatus.
var (
	ItemStatus_name = map[int32]string{
		0: "ITEM_STATUS_UNSPECIFIED",
		1: "ITEM_STATUS_ACTIVE",
		2: "ITEM_STATUS_INACTIVE",
		3: "ITEM_STATUS_OUT_OF_STOCK",
		4: "ITEM_STATUS_DISCONTINUED",
	}
	ItemStatus_value = map[string]int32{
		"ITEM_STATUS_UNSPECIFIED":  0,
		"ITEM_STATUS_ACTIVE":       1,
		"ITEM_STATUS_INACTIVE":     2,
		"ITEM_STATUS_OUT_OF_STOCK": 3,
		"ITEM_STATUS_DISCONTINUED": 4,
	}
)

func (x ItemStatus) Enum() *ItemStatus {
	p := new(ItemStatus)
	*p = x
	return p
}

func (x ItemStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ItemStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_store_proto_enumTypes[1].Descriptor()
}

func (ItemStatus) Type() protoreflect.EnumType {
	return &file_store_proto_enumTypes[1]
}

func (x ItemStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ItemStatus.Descriptor instead.
func (ItemStatus) EnumDescriptor() ([]byte, []int) {
	return file_store_proto_rawDescGZIP(), []int{1}
}

// Item represents a store item with enhanced fields
type Item struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId       int64                  `protobuf:"varint,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"` // Multi-tenancy support
	Name           string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description    string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Price          float64                `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`
	Category       ItemCategory           `protobuf:"varint,6,opt,name=category,proto3,enum=store.v1.ItemCategory" json:"category,omitempty"`
	Status         ItemStatus             `protobuf:"varint,7,opt,name=status,proto3,enum=store.v1.ItemStatus" json:"status,omitempty"`
	Sku            string                 `protobuf:"bytes,8,opt,name=sku,proto3" json:"sku,omitempty"`                                              // Stock Keeping Unit
	InventoryCount int32                  `protobuf:"varint,9,opt,name=inventory_count,json=inventoryCount,proto3" json:"inventory_count,omitempty"` // Current inventory
	Tags           []string               `protobuf:"bytes,10,rep,name=tags,proto3" json:"tags,omitempty"`                                           // Item tags for categorization
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	CreatedBy      string                 `protobuf:"bytes,13,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"` // User who created the item
	UpdatedBy      string                 `protobuf:"bytes,14,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"` // User who last updated the item
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_store_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_store_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_store_proto_rawDescGZIP(), []int{0}
}

func (x *Item) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Item) GetTenantId() int64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *Item) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Item) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Item) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Item) GetCategory() ItemCategory {
	if x != nil {
		return x.Category
	}
	return ItemCategory_ITEM_CATEGORY_UNSPECIFIED
}

func (x *Item) GetStatus() ItemStatus {
	if x != nil {
		return x.Status
	}
	return ItemStatus_ITEM_STATUS_UNSPECIFIED
}

func (x *Item) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *Item) GetInventoryCount() int32 {
	if x != nil {
		return x.InventoryCount
	}
	return 0
}

func (x *Item) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Item) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Item) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Item) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *Item) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

// CreateItemRequest for creating a new item
type CreateItemRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TenantId       int64                  `protobuf:"varint,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description    string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Price          float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	Category       ItemCategory           `protobuf:"varint,5,opt,name=category,proto3,enum=store.v1.ItemCategory" json:"category,omitempty"`
	Sku            string                 `protobuf:"bytes,6,opt,name=sku,proto3" json:"sku,omitempty"`
	InventoryCount int32                  `protobuf:"varint,7,opt,name=inventory_count,json=inventoryCount,proto3" json:"inventory_count,omitempty"`
	Tags           []string               `protobuf:"bytes,8,rep,name=tags,proto3" json:"tags,omitempty"`
	CreatedBy      string                 `protobuf:"bytes,9,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateItemRequest) Reset() {
	*x = CreateItemRequest{}
	mi := &file_store_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateItemRequest) ProtoMessage() {}

func (x *CreateItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_store_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateItemRequest.ProtoReflect.Descriptor instead.
func (*CreateItemRequest) Descriptor() ([]byte, []int) {
	return file_store_proto_rawDescGZIP(), []int{1}
}

func (x *CreateItemRequest) GetTenantId() int64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *CreateItemRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateItemRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateItemRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateItemRequest) GetCategory() ItemCategory {
	if x != nil {
		return x.Category
	}
	return ItemCategory_ITEM_CATEGORY_UNSPECIFIED
}

func (x *CreateItemRequest) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *CreateItemRequest) GetInventoryCount() int32 {
	if x != nil {
		return x.InventoryCount
	}
	return 0
}

func (x *CreateItemRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *CreateItemRequest) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

type CreateItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *Item                  `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateItemResponse) Reset() {
	*x = CreateItemResponse{}
	mi := &file_store_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateItemResponse) ProtoMessage() {}

func (x *CreateItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_store_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateItemResponse.ProtoReflect.Descriptor instead.
func (*CreateItemResponse) Descriptor() ([]byte, []int) {
	return file_store_proto_rawDescGZIP(), []int{2}
}

func (x *CreateItemResponse) GetItem() *Item {
	if x != nil {
		return x.Item
	}
	return nil
}

// GetItemRequest for retrieving an item
type GetItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      int64                  `protobuf:"varint,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemRequest) Reset() {
	*x = GetItemRequest{}
	mi := &file_store_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemRequest) ProtoMessage() {}

func (x *GetItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_store_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemRequest.ProtoReflect.Descriptor instead.
func (*GetItemRequest) Descriptor() ([]byte, []int) {
	return file_store_proto_rawDescGZIP(), []int{3}
}

func (x *GetItemRequest) GetTenantId() int64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *GetItemRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *Item                  `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemResponse) Reset() {
	*x = GetItemResponse{}
	mi := &file_store_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemResponse) ProtoMessage() {}

func (x *GetItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_store_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemResponse.ProtoReflect.Descriptor instead.
func (*GetItemResponse) Descriptor() ([]byte, []int) {
	return file_store_proto_rawDescGZIP(), []int{4}
}

func (x *GetItemResponse) GetItem() *Item {
	if x != nil {
		return x.Item
	}
	return nil
}

// UpdateItemRequest for updating an existing item
type UpdateItemRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TenantId       int64                  `protobuf:"varint,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Id             string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description    string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Price          float64                `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`
	Category       ItemCategory           `protobuf:"varint,6,opt,name=category,proto3,enum=store.v1.ItemCategory" json:"category,omitempty"`
	Status         ItemStatus             `protobuf:"varint,7,opt,name=status,proto3,enum=store.v1.ItemStatus" json:"status,omitempty"`
	Sku            string                 `protobuf:"bytes,8,opt,name=sku,proto3" json:"sku,omitempty"`
	InventoryCount int32                  `protobuf:"varint,9,opt,name=inventory_count,json=inventoryCount,proto3" json:"inventory_count,omitempty"`
	Tags           []string               `protobuf:"bytes,10,rep,name=tags,proto3" json:"tags,omitempty"`
	UpdatedBy      string                 `protobuf:"bytes,11,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateItemRequest) Reset() {
	*x = UpdateItemRequest{}
	mi := &file_store_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateItemRequest) ProtoMessage() {}

func (x *UpdateItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_store_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateItemRequest.ProtoReflect.Descriptor instead.
func (*UpdateItemRequest) Descriptor() ([]byte, []int) {
	return file_store_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateItemRequest) GetTenantId() int64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *UpdateItemRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateItemRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateItemRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateItemRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *UpdateItemRequest) GetCategory() ItemCategory {
	if x != nil {
		return x.Category
	}
	return ItemCategory_ITEM_CATEGORY_UNSPECIFIED
}

func (x *UpdateItemRequest) GetStatus() ItemStatus {
	if x != nil {
		return x.Status
	}
	return ItemStatus_ITEM_STATUS_UNSPECIFIED
}

func (x *UpdateItemRequest) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *UpdateItemRequest) GetInventoryCount() int32 {
	if x != nil {
		return x.InventoryCount
	}
	return 0
}

func (x *UpdateItemRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *UpdateItemRequest) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

type UpdateItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *Item                  `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateItemResponse) Reset() {
	*x = UpdateItemResponse{}
	mi := &file_store_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateItemResponse) ProtoMessage() {}

func (x *UpdateItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_store_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateItemResponse.ProtoReflect.Descriptor instead.
func (*UpdateItemResponse) Descriptor() ([]byte, []int) {
	return file_store_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateItemResponse) GetItem() *Item {
	if x != nil {
		return x.Item
	}
	return nil
}

// DeleteItemRequest for removing an item
type DeleteItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      int64                  `protobuf:"varint,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteItemRequest) Reset() {
	*x = DeleteItemRequest{}
	mi := &file_store_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteItemRequest) ProtoMessage() {}

func (x *DeleteItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_store_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteItemRequest.ProtoReflect.Descriptor instead.
func (*DeleteItemRequest) Descriptor() ([]byte, []int) {
	return file_store_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteItemRequest) GetTenantId() int64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *DeleteItemRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteItemResponse) Reset() {
	*x = DeleteItemResponse{}
	mi := &file_store_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteItemResponse) ProtoMessage() {}

func (x *DeleteItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_store_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteItemResponse.ProtoReflect.Descriptor instead.
func (*DeleteItemResponse) Descriptor() ([]byte, []int) {
	return file_store_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteItemResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// ListItemsRequest for listing items with filtering and pagination
type ListItemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      int64                  `protobuf:"varint,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Category      ItemCategory           `protobuf:"varint,2,opt,name=category,proto3,enum=store.v1.ItemCategory" json:"category,omitempty"` // Optional: filter by category
	Status        ItemStatus             `protobuf:"varint,3,opt,name=status,proto3,enum=store.v1.ItemStatus" json:"status,omitempty"`       // Optional: filter by status
	SearchQuery   string                 `protobuf:"bytes,4,opt,name=search_query,json=searchQuery,proto3" json:"search_query,omitempty"`    // Optional: search in name/description
	PageSize      int32                  `protobuf:"varint,5,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`            // Page size (default 100)
	PageToken     string                 `protobuf:"bytes,6,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`          // Pagination token
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListItemsRequest) Reset() {
	*x = ListItemsRequest{}
	mi := &file_store_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListItemsRequest) ProtoMessage() {}

func (x *ListItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_store_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListItemsRequest.ProtoReflect.Descriptor instead.
func (*ListItemsRequest) Descriptor() ([]byte, []int) {
	return file_store_proto_rawDescGZIP(), []int{9}
}

func (x *ListItemsRequest) GetTenantId() int64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *ListItemsRequest) GetCategory() ItemCategory {
	if x != nil {
		return x.Category
	}
	return ItemCategory_ITEM_CATEGORY_UNSPECIFIED
}

func (x *ListItemsRequest) GetStatus() ItemStatus {
	if x != nil {
		return x.Status
	}
	return ItemStatus_ITEM_STATUS_UNSPECIFIED
}

func (x *ListItemsRequest) GetSearchQuery() string {
	if x != nil {
		return x.SearchQuery
	}
	return ""
}

func (x *ListItemsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListItemsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListItemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Item                `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	TotalCount    int32                  `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"` // Total number of items (for UI pagination)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListItemsResponse) Reset() {
	*x = ListItemsResponse{}
	mi := &file_store_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListItemsResponse) ProtoMessage() {}

func (x *ListItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_store_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListItemsResponse.ProtoReflect.Descriptor instead.
func (*ListItemsResponse) Descriptor() ([]byte, []int) {
	return file_store_proto_rawDescGZIP(), []int{10}
}

func (x *ListItemsResponse) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListItemsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListItemsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// UpdateInventoryRequest for updating item inventory
type UpdateInventoryRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TenantId       int64                  `protobuf:"varint,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ItemId         string                 `protobuf:"bytes,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	QuantityChange int32                  `protobuf:"varint,3,opt,name=quantity_change,json=quantityChange,proto3" json:"quantity_change,omitempty"` // Can be positive (add) or negative (subtract)
	Reason         string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`                                        // Reason for inventory change
	UpdatedBy      string                 `protobuf:"bytes,5,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateInventoryRequest) Reset() {
	*x = UpdateInventoryRequest{}
	mi := &file_store_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateInventoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateInventoryRequest) ProtoMessage() {}

func (x *UpdateInventoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_store_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateInventoryRequest.ProtoReflect.Descriptor instead.
func (*UpdateInventoryRequest) Descriptor() ([]byte, []int) {
	return file_store_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateInventoryRequest) GetTenantId() int64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *UpdateInventoryRequest) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *UpdateInventoryRequest) GetQuantityChange() int32 {
	if x != nil {
		return x.QuantityChange
	}
	return 0
}

func (x *UpdateInventoryRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *UpdateInventoryRequest) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

type UpdateInventoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *Item                  `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	PreviousCount int32                  `protobuf:"varint,2,opt,name=previous_count,json=previousCount,proto3" json:"previous_count,omitempty"` // Previous inventory count
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateInventoryResponse) Reset() {
	*x = UpdateInventoryResponse{}
	mi := &file_store_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateInventoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateInventoryResponse) ProtoMessage() {}

func (x *UpdateInventoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_store_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateInventoryResponse.ProtoReflect.Descriptor instead.
func (*UpdateInventoryResponse) Descriptor() ([]byte, []int) {
	return file_store_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateInventoryResponse) GetItem() *Item {
	if x != nil {
		return x.Item
	}
	return nil
}

func (x *UpdateInventoryResponse) GetPreviousCount() int32 {
	if x != nil {
		return x.PreviousCount
	}
	return 0
}

var File_store_proto protoreflect.FileDescriptor

const file_store_proto_rawDesc = "" +
	"\n" +
	"\vstore.proto\x12\bstore.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe4\x03\n" +
	"\x04Item\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\x03R\btenantId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x01R\x05price\x122\n" +
	"\bcategory\x18\x06 \x01(\x0e2\x16.store.v1.ItemCategoryR\bcategory\x12,\n" +
	"\x06status\x18\a \x01(\x0e2\x14.store.v1.ItemStatusR\x06status\x12\x10\n" +
	"\x03sku\x18\b \x01(\tR\x03sku\x12'\n" +
	"\x0finventory_count\x18\t \x01(\x05R\x0einventoryCount\x12\x12\n" +
	"\x04tags\x18\n" +
	" \x03(\tR\x04tags\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"created_by\x18\r \x01(\tR\tcreatedBy\x12\x1d\n" +
	"\n" +
	"updated_by\x18\x0e \x01(\tR\tupdatedBy\"\x9e\x02\n" +
	"\x11CreateItemRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\x03R\btenantId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x122\n" +
	"\bcategory\x18\x05 \x01(\x0e2\x16.store.v1.ItemCategoryR\bcategory\x12\x10\n" +
	"\x03sku\x18\x06 \x01(\tR\x03sku\x12'\n" +
	"\x0finventory_count\x18\a \x01(\x05R\x0einventoryCount\x12\x12\n" +
	"\x04tags\x18\b \x03(\tR\x04tags\x12\x1d\n" +
	"\n" +
	"created_by\x18\t \x01(\tR\tcreatedBy\"8\n" +
	"\x12CreateItemResponse\x12\"\n" +
	"\x04item\x18\x01 \x01(\v2\x0e.store.v1.ItemR\x04item\"=\n" +
	"\x0eGetItemRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\x03R\btenantId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"5\n" +
	"\x0fGetItemResponse\x12\"\n" +
	"\x04item\x18\x01 \x01(\v2\x0e.store.v1.ItemR\x04item\"\xdc\x02\n" +
	"\x11UpdateItemRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\x03R\btenantId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x01R\x05price\x122\n" +
	"\bcategory\x18\x06 \x01(\x0e2\x16.store.v1.ItemCategoryR\bcategory\x12,\n" +
	"\x06status\x18\a \x01(\x0e2\x14.store.v1.ItemStatusR\x06status\x12\x10\n" +
	"\x03sku\x18\b \x01(\tR\x03sku\x12'\n" +
	"\x0finventory_count\x18\t \x01(\x05R\x0einventoryCount\x12\x12\n" +
	"\x04tags\x18\n" +
	" \x03(\tR\x04tags\x12\x1d\n" +
	"\n" +
	"updated_by\x18\v \x01(\tR\tupdatedBy\"8\n" +
	"\x12UpdateItemResponse\x12\"\n" +
	"\x04item\x18\x01 \x01(\v2\x0e.store.v1.ItemR\x04item\"@\n" +
	"\x11DeleteItemRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\x03R\btenantId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\".\n" +
	"\x12DeleteItemResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xf0\x01\n" +
	"\x10ListItemsRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\x03R\btenantId\x122\n" +
	"\bcategory\x18\x02 \x01(\x0e2\x16.store.v1.ItemCategoryR\bcategory\x12,\n" +
	"\x06status\x18\x03 \x01(\x0e2\x14.store.v1.ItemStatusR\x06status\x12!\n" +
	"\fsearch_query\x18\x04 \x01(\tR\vsearchQuery\x12\x1b\n" +
	"\tpage_size\x18\x05 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x06 \x01(\tR\tpageToken\"\x82\x01\n" +
	"\x11ListItemsResponse\x12$\n" +
	"\x05items\x18\x01 \x03(\v2\x0e.store.v1.ItemR\x05items\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x05R\n" +
	"totalCount\"\xae\x01\n" +
	"\x16UpdateInventoryRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\x03R\btenantId\x12\x17\n" +
	"\aitem_id\x18\x02 \x01(\tR\x06itemId\x12'\n" +
	"\x0fquantity_change\x18\x03 \x01(\x05R\x0equantityChange\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\x12\x1d\n" +
	"\n" +
	"updated_by\x18\x05 \x01(\tR\tupdatedBy\"d\n" +
	"\x17UpdateInventoryResponse\x12\"\n" +
	"\x04item\x18\x01 \x01(\v2\x0e.store.v1.ItemR\x04item\x12%\n" +
	"\x0eprevious_count\x18\x02 \x01(\x05R\rpreviousCount*\xb3\x01\n" +
	"\fItemCategory\x12\x1d\n" +
	"\x19ITEM_CATEGORY_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19ITEM_CATEGORY_ELECTRONICS\x10\x01\x12\x1a\n" +
	"\x16ITEM_CATEGORY_CLOTHING\x10\x02\x12\x17\n" +
	"\x13ITEM_CATEGORY_BOOKS\x10\x03\x12\x16\n" +
	"\x12ITEM_CATEGORY_HOME\x10\x04\x12\x18\n" +
	"\x14ITEM_CATEGORY_SPORTS\x10\x05*\x97\x01\n" +
	"\n" +
	"ItemStatus\x12\x1b\n" +
	"\x17ITEM_STATUS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12ITEM_STATUS_ACTIVE\x10\x01\x12\x18\n" +
	"\x14ITEM_STATUS_INACTIVE\x10\x02\x12\x1c\n" +
	"\x18ITEM_STATUS_OUT_OF_STOCK\x10\x03\x12\x1c\n" +
	"\x18ITEM_STATUS_DISCONTINUED\x10\x042\xc7\x03\n" +
	"\fStoreService\x12G\n" +
	"\n" +
	"CreateItem\x12\x1b.store.v1.CreateItemRequest\x1a\x1c.store.v1.CreateItemResponse\x12>\n" +
	"\aGetItem\x12\x18.store.v1.GetItemRequest\x1a\x19.store.v1.GetItemResponse\x12G\n" +
	"\n" +
	"UpdateItem\x12\x1b.store.v1.UpdateItemRequest\x1a\x1c.store.v1.UpdateItemResponse\x12G\n" +
	"\n" +
	"DeleteItem\x12\x1b.store.v1.DeleteItemRequest\x1a\x1c.store.v1.DeleteItemResponse\x12D\n" +
	"\tListItems\x12\x1a.store.v1.ListItemsRequest\x1a\x1b.store.v1.ListItemsResponse\x12V\n" +
	"\x0fUpdateInventory\x12 .store.v1.UpdateInventoryRequest\x1a!.store.v1.UpdateInventoryResponseB7Z5github.com/rinsecrm/store-service/proto/go;storeprotob\x06proto3"

var (
	file_store_proto_rawDescOnce sync.Once
	file_store_proto_rawDescData []byte
)

func file_store_proto_rawDescGZIP() []byte {
	file_store_proto_rawDescOnce.Do(func() {
		file_store_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_store_proto_rawDesc), len(file_store_proto_rawDesc)))
	})
	return file_store_proto_rawDescData
}

var file_store_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_store_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_store_proto_goTypes = []any{
	(ItemCategory)(0),               // 0: store.v1.ItemCategory
	(ItemStatus)(0),                 // 1: store.v1.ItemStatus
	(*Item)(nil),                    // 2: store.v1.Item
	(*CreateItemRequest)(nil),       // 3: store.v1.CreateItemRequest
	(*CreateItemResponse)(nil),      // 4: store.v1.CreateItemResponse
	(*GetItemRequest)(nil),          // 5: store.v1.GetItemRequest
	(*GetItemResponse)(nil),         // 6: store.v1.GetItemResponse
	(*UpdateItemRequest)(nil),       // 7: store.v1.UpdateItemRequest
	(*UpdateItemResponse)(nil),      // 8: store.v1.UpdateItemResponse
	(*DeleteItemRequest)(nil),       // 9: store.v1.DeleteItemRequest
	(*DeleteItemResponse)(nil),      // 10: store.v1.DeleteItemResponse
	(*ListItemsRequest)(nil),        // 11: store.v1.ListItemsRequest
	(*ListItemsResponse)(nil),       // 12: store.v1.ListItemsResponse
	(*UpdateInventoryRequest)(nil),  // 13: store.v1.UpdateInventoryRequest
	(*UpdateInventoryResponse)(nil), // 14: store.v1.UpdateInventoryResponse
	(*timestamppb.Timestamp)(nil),   // 15: google.protobuf.Timestamp
}
var file_store_proto_depIdxs = []int32{
	0,  // 0: store.v1.Item.category:type_name -> store.v1.ItemCategory
	1,  // 1: store.v1.Item.status:type_name -> store.v1.ItemStatus
	15, // 2: store.v1.Item.created_at:type_name -> google.protobuf.Timestamp
	15, // 3: store.v1.Item.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 4: store.v1.CreateItemRequest.category:type_name -> store.v1.ItemCategory
	2,  // 5: store.v1.CreateItemResponse.item:type_name -> store.v1.Item
	2,  // 6: store.v1.GetItemResponse.item:type_name -> store.v1.Item
	0,  // 7: store.v1.UpdateItemRequest.category:type_name -> store.v1.ItemCategory
	1,  // 8: store.v1.UpdateItemRequest.status:type_name -> store.v1.ItemStatus
	2,  // 9: store.v1.UpdateItemResponse.item:type_name -> store.v1.Item
	0,  // 10: store.v1.ListItemsRequest.category:type_name -> store.v1.ItemCategory
	1,  // 11: store.v1.ListItemsRequest.status:type_name -> store.v1.ItemStatus
	2,  // 12: store.v1.ListItemsResponse.items:type_name -> store.v1.Item
	2,  // 13: store.v1.UpdateInventoryResponse.item:type_name -> store.v1.Item
	3,  // 14: store.v1.StoreService.CreateItem:input_type -> store.v1.CreateItemRequest
	5,  // 15: store.v1.StoreService.GetItem:input_type -> store.v1.GetItemRequest
	7,  // 16: store.v1.StoreService.UpdateItem:input_type -> store.v1.UpdateItemRequest
	9,  // 17: store.v1.StoreService.DeleteItem:input_type -> store.v1.DeleteItemRequest
	11, // 18: store.v1.StoreService.ListItems:input_type -> store.v1.ListItemsRequest
	13, // 19: store.v1.StoreService.UpdateInventory:input_type -> store.v1.UpdateInventoryRequest
	4,  // 20: store.v1.StoreService.CreateItem:output_type -> store.v1.CreateItemResponse
	6,  // 21: store.v1.StoreService.GetItem:output_type -> store.v1.GetItemResponse
	8,  // 22: store.v1.StoreService.UpdateItem:output_type -> store.v1.UpdateItemResponse
	10, // 23: store.v1.StoreService.DeleteItem:output_type -> store.v1.DeleteItemResponse
	12, // 24: store.v1.StoreService.ListItems:output_type -> store.v1.ListItemsResponse
	14, // 25: store.v1.StoreService.UpdateInventory:output_type -> store.v1.UpdateInventoryResponse
	20, // [20:26] is the sub-list for method output_type
	14, // [14:20] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_store_proto_init() }
func file_store_proto_init() {
	if File_store_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_store_proto_rawDesc), len(file_store_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_store_proto_goTypes,
		DependencyIndexes: file_store_proto_depIdxs,
		EnumInfos:         file_store_proto_enumTypes,
		MessageInfos:      file_store_proto_msgTypes,
	}.Build()
	File_store_proto = out.File
	file_store_proto_goTypes = nil
	file_store_proto_depIdxs = nil
}
